hash-format = "sha256"

[[files]]
file = "index.html"
hash = "3ab4c5527f2bdb07b7f20cb2a8aba045333113abd5bcd8f071b0d7b627644e12"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "a3b61a22c5443c62fa556d8d3702a31727f83dff788992bb6cb9e85689ba3e61"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "79e4567a56a1d4af7a2fe61325d090685268883fbd85b193f9793aece9c6cc1e"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
hash = "913247bbcbf08b1689e3d72256eb8932635388a956e3279ec9b650c493205a56"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "cba26f438c185ab8cb33f549e78e8a46baf40294c14e63509bcb87035308a1d7"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "d45e033df1a9ebc0eb0d66f100f1773f1800ca7c53b07e5e6881ce38965eade0"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
hash = "c3d400a6fd0b217aaeff603707d7964e52ae2fbc9df5d932740311d3503b6681"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "5c9341b9cb48424fe1c08f081cbb3aa19a46e7e31ffd551df421b943891642a8"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "8f96ee6a786812f7d07824c838d60b56e6eee6139c00a158c43f3459c02d927a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "957f447037e778eec0de9370cfad61ff804bcc0c67ba52516fe5e6b5fbad2b2f"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "7495abb08e7df662bf47a549c10d7833d2365bbf375b20136c1e09c0c21a9765"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "e6f7d05a47c717cbdef4b105f44d71b2f3202154e2517d6641d6661d01cad07c"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "647c853be12135d69731a79e96e56c9ebef01f255a5e456b73ff2e954e0b1355"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "113e971e1a3d588d43beedef5702d8dd40abf150d99b6d0d82f39c2bc381335d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "455c662cc51dec506f65b8989db19650093be75b704f2c674e8375c32e016a58"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "56c1f770131880c2e484aa4dfd29b65be6358dee2eca827fb0a4746358837cb0"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "64e0b406a14dc607b88ac95f7f2bbcc8a3e7ca95b13a9f171cc66beef7eeeda7"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "94a1f6d77920d815b3ae8fe10b58c9d2bc4df5fdbe2c53a07e55dcdb4e8bd0be"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ee23e2c15742421bd42726c87c1212571faf021af09ea1bc2974b63e5386fb90"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "453bcef1f941857dc0f17eef5ff9e1f7fec6dbc9aff2ad1c3d5c75a698dbc509"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "02ce09e64c6ed4f5484b1496201ad411e78561812c3008e6c1bdd6dfab63e616"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
hash = "ae695c45faaba1057acf9a7c0f228c58d83da17fba38fd4ea96fd08e84f7a26b"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "f2ca3c2ef10cb90a25deef0e8bfb9198ce9d6beb6b740c307816f864a1f116c5"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "777a760b75f526b9038a60aedb6da639100efae805ba73d089e332175d530c2b"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "9962f073ca683f9d979b62b97e9dc5a44072a58bc9121af3c9719f004085f61e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "85ebb0df9d958fede547f04d88b59d71284e919a27f152f60b3c03563cac22f5"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "96a3463c6b05867e7ed2cf98bd7faed2b8d190913d9d8f9b551bbae6eab8efe4"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "227d5fb4edfae4f5692879c81ed765b23af1f1e765957d52b2ba9fb065f04b55"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
hash = "c04c1d8431d3cd9f83afdf6fe58e922a585d071cdef58e621049a0506b401538"
metafile = true

[[files]]
file = "mods/crooked-crooks.pw.toml"
hash = "2931a533d997e9d242eef80f0602c0d1b0c311e9bfc915ddd2e188e0e75ae1bd"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "8c594cadc0cb0aff268d8b96cdc99d7e9655cf69f5110c1375b7b3e39ee419e9"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "1ed9c179c132edb1b0c9669984c0c332a464e8c842d73c097921f1e3f7c462bf"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "89ba21e3753115ddf5670fd1063dac4f620b8ad8748a7702404a62081730f373"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
hash = "667ec8faf28150179cf141333a99ff91bbf2031560048ec0d8ebbed8f4993ca3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "2db492a7ec0d37888c765c6d3a4a362de8b1539cfcaf97138176cb1e115d5da0"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "2cbcc42cf9c64c4306926ae50259a1d119015e82e67cb4b14a620b2990f63572"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "073bff49ec9e664b669794177329cfbeef3c3d91d5c0660cd01144a640e0338b"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "13189f12fca03470e2bba093e2f70e46e069ed5421ed20a8657cab71d8897c30"
metafile = true

[[files]]
file = "mods/enchanted-vertical-slabs.pw.toml"
hash = "e650e9f1b9fb0adc54eace767decb72980f5a77ddd99e012146cf903fc6d7ee7"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fb056d772175c202b054fd2fa32ff8c3f98e618249f1078b8f2c6b24997a0f13"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1f47872fdf0e954fe7dab437208f9c86f10812284aad39c7d3ae8ca13d906b89"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "62a23f62fdb1a11a69ddb99a73aed8f11fb8691b03e87593478f1b7c9a2de5d5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "674b69231bf37773aadd3a03e40288abbf0ea312b6a662b200db488b8942bbd9"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "0370c8b089c61cd96a8d82c8d60c727f7c3cb3df04854a3d97d6222ef1eb2eab"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "697cd517fc80a11dd3f7caf66dee0d1337a055354773256eacd10a263f2849ee"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "87f056062378f276e55d07a577ff6c734bb9af9ea2b5591c424f7c381f82a552"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "6740ed944875ddd29d44b38bb88fd5050f600d44ff30ff3d553cbb9394254d8c"
metafile = true

[[files]]
file = "mods/frame-api.pw.toml"
hash = "061c9e60ebb529f31147c5a6c61a1d2eafb40dd9c97ee82fdd56b035b7946c9c"
metafile = true

[[files]]
file = "mods/friends-and-foes-quilt.pw.toml"
hash = "440d8b8f3e0466aa27eb34fa4b4dbfb2b4a5f0cdc5d3c8d0db8c59a45805417a"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "ee592d0ee17bcd647333960d15e303ae7fe603194f9e3f069f61ea2486537122"
metafile = true

[[files]]
file = "mods/grass-kiss.pw.toml"
hash = "12617693bff87d99412983127b4b44989e51f33611ee330db484a3e974f09f27"
metafile = true

[[files]]
file = "mods/grid.pw.toml"
hash = "7da46a17a45e08854ef0fae0734b02512d9a6a6bbc157402445f92f851a4e78f"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "645884cfb77a80f09ec53ed044778e42632dabc125756977506dd1ddee546cbd"
metafile = true

[[files]]
file = "mods/horseinboat.pw.toml"
hash = "4bcc4a258aee210d59bcfa1b455ed631f337b20ae21cfe97cf37236d2102dd58"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5dc09aa39836e32c785297fd6e34c70e1ca9cb80264da8b088e0bc166b69d9e9"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "8bab32d19a8d82d8b61e52d0fefdc20d5587550cc4b0d2f901419abeb5548660"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "5e28a60fdd6e769e61e7b791bd6c54eebbb2251815031d615f5435b33e9ec710"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9870d86c56f25115c79ade562b9605c98af9b0b1ea13d3e93c4e8390be52f5b0"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2bd6bb34cc34e9010c35d30ef21e71fa63386c6a7b2bbe16f7c1369db10c693f"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "21edb2e112a0ead52b9dd25f6679b5f986ffe2ddbc9283042e31f6613026fb5a"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "94690110840b6ac0d257ce753a5d2ef91f85762d7eab874a6ab1922c4d504ce5"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "3ffe2388740cc111a332082f56e37bb4b95764035dfe5d6dff81db8a35d4cc4d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e7986bc23e319e750e19139d68f1facec6df41d98d51d417293c5c1434e7f845"
metafile = true

[[files]]
file = "mods/megane.pw.toml"
hash = "2219826da2fbb44f37c5eef91059154d55d43dc16a57188fc6376709568908bd"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "a8f38c0adf08de0ea8a04120a0ce2cb20db8084527958b8e97a3bc21453b9916"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "304073cded20a12559a95bb7352d0d90b5e6615e8035ac8a96c84662f33b81ad"
metafile = true

[[files]]
file = "mods/modern-dynamics.pw.toml"
hash = "05d66a75eb6947fe1d74479221572d2d0b5fa347cf126fa2ce9561865602d501"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "dfa5c722d138df87aafa11fee3b7566b0fcff8adf155eed9f478d08436ec9f9f"
metafile = true

[[files]]
file = "mods/nether-chest.pw.toml"
hash = "3ac1e7f3b28a7350ba416dd8c8d9778ae066dd62d278bb6540512503a25771ec"
metafile = true

[[files]]
file = "mods/nmuk.pw.toml"
hash = "a83d198f3585289820eff26fac20e0922da53906b1a607695ef8cc6dba668cf5"
metafile = true

[[files]]
file = "mods/numismatic-overhaul.pw.toml"
hash = "58d53de276d954ba769c52e2a64b96258a9350a56620061eed7c2f581b06d22f"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "fbbab6b08ffab24ed1a6c773ab32664398739acd6b5846d676d2b615e2c7b415"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "89096582f8cc0ee3403cb0c0e571f9030ffa51227815f6fa3e232342dd0481b8"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "90a36cb8e705eb50f6e01999362ca855a8c63a30002576049fe323bbee64bb6e"
metafile = true

[[files]]
file = "mods/purpeille.pw.toml"
hash = "75ae8bce9a8abcd4f3df98ec7251d2fcfa05ea76740b634545459a254c4c0e24"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "4f033c8165f561c19dd99c3c4a8017dc3cba9f655f6371582f14118a0ec093b4"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "abac5084638e76db51e4ce0b456682c78e701517eb561b8037d429ff78ba205c"
metafile = true

[[files]]
file = "mods/red-bits.pw.toml"
hash = "217142343f686f6b94a2b0e93d2fddde2e5d127e0648e40e9364976cfcb82f6b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "f8784a0fc67a28151c4b19fd6b8aab83cf76843aed4c49be5df6441a3e3c4960"
metafile = true

[[files]]
file = "mods/scout.pw.toml"
hash = "c7d3298f267e69edbfcc5957b0a0ce5787414f832cfdbfa13a2e7e841583d0e9"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "20c9880521f1b1d1e6adb45323195b75512b3de52c187868845b593fbe833c9f"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "3271fc1c210bc8c2dcd1cd58d80c683f4f7e6a3077c079920054b4483dcbcb33"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c77f162c7072a9bb922faf3bd5f223ce4f57973d531cc32484a7dcf72d2e1f51"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4eac7457b81881fb5e2d38f45800acbc9a249bc27f9b7872c8d035fc619e3f46"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1651ee5e299d8883a2aaa8956cef6818d8f8686410d83f1d153a944deb650bf2"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "c429a2b5d2a8e85472f4625c786fa407ea80cfe9ab8d9aedbbf2a00f0a7467d8"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "5b02ff4b479157c4fcce8582b29c193583d96606296fadcfe0e67c65c5780bf5"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "eb9ee2a2f560d3fef5a2c3cd3abdda508467bc4b1c75550f7e6a7baf3638815d"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "7546192a8fd2f45b347a5f5725008fc95d686dcb8a06f0c235dfd15f33d3d2b6"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "abd084a63c3fc923ee86d5dba8e6a11e5ae6b552f183f141475e09b38f035545"
metafile = true

[[files]]
file = "mods/wandering-collector.pw.toml"
hash = "a6dc2a336d9802c368da50c9deb24828c4489c281f770971d789012b49b82c99"
metafile = true

[[files]]
file = "mods/wmitaf.pw.toml"
hash = "f0393f77b82f7bc0d88783ce7c8e9068b450a1e9bc94d445d6884e24c8641364"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "f1727131f831c6b2e98d561de89bec3ebe3297d4c0b332c246a9a8844d76ec1a"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2bc3242a6a026024a2048e0051c0efed79d159e72d6ea361da847acbc6f68da5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "aadfbc4526184f6f67b36305e6c1a3386858423998716de94392ec96ad5404b0"
metafile = true

[[files]]
file = "notes.txt"
hash = "6afa7b16f267282aba9fb7901c875eb33a093e28f384726c118af7aa89b95215"
