hash-format = "sha256"

[[files]]
file = "index.html"
hash = "3ab4c5527f2bdb07b7f20cb2a8aba045333113abd5bcd8f071b0d7b627644e12"

[[files]]
file = "mods/addadd.pw.toml"
hash = "21045286366a40ebfe18316a4361ef4e2360f7f06fb0dda95876f71ed4d19a1e"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "799fb74a161affb990a77127eab92170c276be67b04f83483f77c589686d9897"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "e36054ef110c3a29780b2c362334880d07ccd02eeb78251d60446d4bb0181029"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
hash = "ec3e39d6d699a359b42a4085c21c674842edf8bb6e16c8371da01bbdf2ff559e"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "389e7290f83d189497aafb4a571d340a68df9dba183b5ee1b8ec33af112f2c70"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "a319fcf82f12b73743c4b3980014acd3a77f6e656008851d0c1710d2bc45e351"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
hash = "cc9f01ee3843017d1bf085a75c940b43d5de50144e7c872b8f6387b315340a8b"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "c00121bf6d69a7dbbf337f8e4644a05462cfdd9cf644cd043290e79877d97444"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "4dcff88a019fcadc68fc822c33668eb56f21916cf2dc062c7d727eafa3ebc49c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ef2f98e5477d6b3400cdd292c01ca6a8a2d038421ef142be83658663ecb8a06e"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "f2f74b24a08a7e4fd4ea09f101cf7bdc92f4762ace8ddbabaa2325ded3994e48"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "7fa71207025c9e2c4a619a0a3bfc18972df624d7c7554ed4e450f1d28cdf2b57"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "113e971e1a3d588d43beedef5702d8dd40abf150d99b6d0d82f39c2bc381335d"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
hash = "f42912a8bcb5d534263ad1a379db8fea30f4d260a858a209aaddadb977b90068"
metafile = true

[[files]]
file = "mods/betterdarkmode.pw.toml"
hash = "d85b71cd9bc9a78c061892c5b09b04f743f1b0afca47de689ad3e2f2bbc426ca"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8a399348ac3cf537118f171c78e464d83db3df13ce3dbafad1eb5050cb078acf"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "5ce4fcd19b003dda52008a56f78118dd687abaffb8405399f5deb4c06fa4b30d"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "d123f5087fffb81765fae130cdb14be9e9866612dc2ac13f11193d8fbf860fe3"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "eb65e1d2cbc12e600830572fa297f01a7d065484af541feb563da1756f32be46"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "60ddaabceb126b260d122c1eb927be91d4907bee4f78fe810db2ce50ed1ad11a"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "edaa166c7eaf775d7c8bd309eaac83ed386bd68b811ab4ef54e6e0ea98747dae"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "6a34e4ac98c8bb45e15a05f2d51bdb4d35ffbedecaf3984b60aec663ad06c425"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
hash = "e8b13259469fb55e713d7b870bbf28f8a969689b22a3578d198c773e463ec4ef"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "a11e765e71da3d4b1369d2b0a4fbb1c1cbe10e1f7755b0429a92480845e33204"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "be5be95ba875312d06e69ced489b272a6fe3752066792696051c9c0e24de36bb"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "bbe2dbc35ecbee84e62b52b159ae1f46322d10eb2485617222d20edf69b2ac52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "db04b2cbd572d20095051ad2cd2d6663ab7d6b2e74f2a7849d46427d62db850a"
metafile = true

[[files]]
file = "mods/connecteddoors.pw.toml"
hash = "6b2d266f73dd7c2d03a0fbb039432a32be3378cac25b9633965488daa36e91d2"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "e1c1f057a2649f03a012eec8429559e73d0fd1b74ecfc571bc628fdb68c5bbee"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
hash = "94d1323f289eb0cfe35fd28f5ddbdd24db00a967769052f27cde2c4df20e7d03"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "93621844bf5b4c38e52819b8f0c705590ee0bc98428fe76bc071b9fb4b782754"
metafile = true

[[files]]
file = "mods/createplus.pw.toml"
hash = "474bcdc08d295459517dd739a03006dd1a9b212a304be22de4b6200fb0431931"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "241d75b86faea9b4218e5eb3b5aba6fb1018f175ff42fc77e10a149f50fafa15"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "4df29a6c6b0fc84557f60a7db850aa54927b2ae974b19283f504fe2b6cf775ec"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0c8d491a83ad47d014b007a99d379558286229c487c67d74f03ac9e10ea88f03"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "f3223247cd2e368ad7096b244faf045d6e58e0818396802fc1a83523b6227555"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "5a20dae79db91b0d9e7bdd37c074e2e68c5e94fdee51777d82ab8c09b210e94d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e075e0b77fafbf166171df8412138fe15cb6d6f6dbbe96129349dce357d70d9c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "5eb43c0791caf0fc03ccbbadf3d68c2c17b3498062f20fb4c516cdcf3dbdd46b"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "7fdde2a2d9d7853c48d672bfe2a43768c6245501e051597f48d5d487cfa83286"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "768f866630b030c141ff8e63991a370f2fbe4d91ca18f2043c08602742715e3d"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "5a098921850ace318496b6c08a4f3c015ea00118b7b8dc7b1934639f89f0123d"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "effbe8f330c3ace2c220749b6d13d8bd51af9979220817ecbc85c26fdc08f8d5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "a4290de69d82b65783d765d714f7fa9500f61e20523efab532a484cc008277bc"
metafile = true

[[files]]
file = "mods/forgetmechunk.pw.toml"
hash = "3b55317680dbcfe2365b68a53274b23c69ac95d36c9102aa11d19db7c2895430"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "e1f51a18b64264d788a7fd5124185027930dd8f4b792ba67067eea011501295e"
metafile = true

[[files]]
file = "mods/grass-kiss.pw.toml"
hash = "dbecdb6462332421c9545d7311e44879633f1ff2f645fe7c096bf93fa4d9d492"
metafile = true

[[files]]
file = "mods/grid.pw.toml"
hash = "e77d82fb0069cf8efb5c35ded083df2106c5e64c6743b5d8d7299d67d9df8bcb"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "8e64e605cb87282d854c4cbc974ff166f3bcd4f989c6eaa511cfa3a82f49d4fc"
metafile = true

[[files]]
file = "mods/horseinboat.pw.toml"
hash = "2639d0134e2f38a08e48471631feda277dd8a8ca16dd2d52aeff495c2e66d4c0"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5e354831a4c011511511ecd10c21d61d1ce421a515a8fd2cb7877838363bc52f"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "e9ab1d59a9395cf616daca190db5781704a4d3acc6902b7f2b7f5ad5e4d98c86"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7cd3675978c77226ea2d2e28101c2a56b3f4b9d8cf1f6f9948f4276febb638bd"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "0874da11116ad385ee260ce4215d2ae6b1bc3fca803e57a90e0d83000fb21635"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "b83942ca0716ab773cf54c0136feaae78a0f74a955796aab6b7a0c6e7cfa2f6c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "ccc84a4677b80c41989ee5cd1ce25cf941b33991b2562d8cbd827a38b8690121"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "726e4eb3df640b4ca141c71ea1de953cc618d1a602d88398d0db6d1810f13b3d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "1faa1d82d7e726cee6aed78fd9c0c9487e57db056f8fb6ebb7c42782dc639032"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "0f76eedad0d3268d9b43564b7c086804ba305ec33c2a32e25e81b8d14044a7eb"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "138fbcb698b3f1e60d1ee4984937a93b8e9b78b002ef99e7e2f1eb248e456bfc"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "d3412535589aee86f0386c6576abcf078349fd9603465ad287e92147a9a789d5"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "2c9ff78bf4460ef80e6fcf3fe4768fe2073f988b6f4c3f9aadeb56c5c675b50e"
metafile = true

[[files]]
file = "mods/nmuk.pw.toml"
hash = "68782b22da1dd16606e6efe706a2b2d8f25f980db4b3d66f201d1a51d64c92b2"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "a2d5078d4a4ecf2142438b971b0632a7e191294cea6ca46bf25c2f90f30cb0d1"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "f400d0482c5e3e0e321adb79c0e4c701280a76d46948b61761182b2713bd8516"
metafile = true

[[files]]
file = "mods/purpeille.pw.toml"
hash = "706ac9854947d5d6552d2682e3cc572b03dca9a67f7bd9a65d74ae7392f098ca"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "41af63db79623830d5564ddbace45bf4909c5f7877349b895c46749ffec0b253"
metafile = true

[[files]]
file = "mods/red-bits.pw.toml"
hash = "594959f772277b0fd3409d9e425918fe7e295048d9b8139fb5d3f19a6c4aee2c"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "07cf673323a941f75a39e65e0896b2b58d43dc8566a14b659e645a1f133c4fb0"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "6b98e8f2e83aee04185a1e4a60560510ec484d8dedbb96dcb4a2d5b2aeb89ec6"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "413a20665999ecefbce3f49fd48e709a62f2a26ffd5e8c0d68223704fa2e6133"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "2a3cb365a541f27463fc54eaa4a72b9d0c5b4d7abd066e897f04d3461ea0a9e7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "887c47918167fa72a4f90028a950df98a6312893630447b5f217568a0aeca129"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "382e69c318c72050fd826930e06b8d5011c834de01c31ef9569b912fdb611dac"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "27b4ce5a9a49224119ff967e52bf49cfb007a25851414cc957769fc64fe68d0c"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "3a3abcddfc02c9e1fb9bdf70d42f2aae7d078aca62f795f37318821cfd00d0a1"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "25833e49fa26dfa7423647007e1387d6dbc755c3250beb72003de665977eaa3b"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "a7e88f25bb759975cfb5a883fa27308db94efa16b1918ebbb2b8080a8cd9cf16"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "93978fc69ca4e6b61acf77ee67b9468bc009a398b7fb9909c1c14291ab60a4fe"
metafile = true

[[files]]
file = "mods/wandering-collector.pw.toml"
hash = "5478b1fd67934a32aa08d7d67f70bd9fcdf8b3827f7cdd7a2b7a89babb8b289c"
metafile = true

[[files]]
file = "mods/wmitaf.pw.toml"
hash = "063b46c0e7f6e54c0486b50d5008609474ee7e492d33b258553acf28a11a9f68"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "a20b7a8fbc4f16825ba68b2741ceebfb658a8837ff57a36db6dad7d9b0adcf7f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "0807c8d30143c8a5184c99a890adf5d7bee5e428565031d5d107d3f4b32e0ddc"
metafile = true
