hash-format = "sha256"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "9f22e2a556a371eb5acf2f7b1e63870f7008fa6c18ed1e4d5b3236ee66828317"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "acf36c8ed89c3d56a2005a22d662ada08511123fc5570e2645bf66439bb11d5e"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
hash = "fd25ba86551687f2adedc74cc6accd93fcb4e0b6d07e8369883736baf175fe48"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "068ec29e5c2383192c89411a3c47909a06f3aa1015c73cfdba1d265283196510"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "93e3b459b8684af56de2e24a22251bb208ea7480d2a93379a95de42ceeba5930"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
hash = "7bd35ab87cc191359f8b7ca64bd6e812ce2cc81f34b75ae22948c2425a2e5e6d"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "09a3690cb476ca830af5c481682052f11f62beb37e818fa34a0474c21371dce9"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "a695f252982b8543008f76543fcbd03fb32f741d5eab003ead7aba5c7834c2b0"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "91096af9b96991b06ac07a6e08fbcfe21c233d623a9e595b8ab60585fb6e5c7b"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "e6f7d05a47c717cbdef4b105f44d71b2f3202154e2517d6641d6661d01cad07c"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "113e971e1a3d588d43beedef5702d8dd40abf150d99b6d0d82f39c2bc381335d"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
hash = "7839c3af6037794000822f4f96c84c842844a9b72ad063193dd9494b46a64d9e"
metafile = true

[[files]]
file = "mods/betterdarkmode.pw.toml"
hash = "dee7be64ab7132f687fefd359228390cb03ae53e320f423da7d8078e66267043"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "1f1143578e44c21c78c7360e92a392a87a1d60cc3be2f25d15e88cce6a765849"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "4bd4a944ed0eb37a16c3f2722d88c0e637e92df0f24ec1a342ab5f3c26b51275"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7d271dfe7ba52243602bfe6fb74c5a3c5f7156142bb5aa24c21db1ce62aba30f"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "4347d29a5aeaabc2ee1711aede87c4dbe4881aeba6ed7136f783a79438a3d3d2"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "4005e222e444336878c881022ca37c346ba194c726acd7e6f258a029566d1f4c"
metafile = true

[[files]]
file = "mods/charm.pw.toml"
hash = "43b890e66def27d2e69144b58270c489aed8b23b2b62133c062cf90bc32dcc46"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "da0c8ca6755f0e2e420d88bdbd23d1c1e132394f387d3c48851963a3221b9475"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "78a43003cc65b4bb865f4a552ebc47c2e61e6ec96039e188b5700d2503e76250"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "374ce345245226fac34fbf06024c3b8478a8b84a9510f52a062fee474b7bfced"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7a3560c83727e3fac4807c6b2cac054569966dd1f09c5883e1ef78988568b45e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "07dc8b6b90eb549554a26a111f05b54e8459dd8150f5f3c146a05c3400b7c7ff"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
hash = "ef01aaae3db24c0449b141dbab5ec6006baa5b41a66aabac6793e75118c63429"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "b8eeaa92aa2dd065415afd6c449f8c785d387a9f27fc5d6e40e35c31ac6616b0"
metafile = true

[[files]]
file = "mods/createplus.pw.toml"
hash = "e0d6530d40d3da9b8909c015e64c921ca7bc2541d53d9539bf6d3099d34aa51a"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "f103f2600d5c7c0c468cc2576803751f0227c68dc2bdbf693606452f3887b540"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "0fb34c3b9433f37dca79aee80937a95772d846c8110b419b2ca659b660fc971d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "09a23d22d146a039769ed8d67f52de31f25648d952aca0ccab8775aa02a4b1f2"
metafile = true

[[files]]
file = "mods/easiervillagertrading.pw.toml"
hash = "432e2989b0a8c2356e6544e3474a8d5f034a741078b2ad82b8f7f655c2ef39f5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "478f43341248346118765f37013fa8d595b9f66aeb3a681146afb29731b4f8f7"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "7bb361ee92cd7031db4be5beab67b5bfc2fb353b3927243a44a496eacfd6808e"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "bcdc122056ef7c363cf97fffbcb656c0eeab76593993f1dec7e69e055519cd99"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "3c3d7e7f9e0ae6a978564276c618a802d0c54c4ca098a7a897252a662ff4723a"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "fb6732e1306d4dd5ef5703e44c2e71b122579e68c056b864f47a0920a6315e9a"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "80bfb2aa2ef862c92581a130e47f95f6dc6ae29f8b02b5423d7147752cf2b00c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "a8870bf1740259a7392af3e5a8a001fe957e9cb3b6a7879a5acfe608d45eaf73"
metafile = true

[[files]]
file = "mods/forgetmechunk.pw.toml"
hash = "bd8c6d669b805accb1d4936edaf9b4890492dacdaca20dfebaacbeeca93d0f8d"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "cef699b8de118b5ffb298ff722c6a6a4bc8d83eac4d0b5c94e0d6a6431b93673"
metafile = true

[[files]]
file = "mods/grass-kiss.pw.toml"
hash = "04b331fef41ca433c893a1757d3de9191ca5de589ef546a92973fb3d8ff5f4d4"
metafile = true

[[files]]
file = "mods/grid.pw.toml"
hash = "d34a62860584b4c2a4991ca49e1120df2a699a0aa319243150e3d2b77e38fc78"
metafile = true

[[files]]
file = "mods/horseinboat.pw.toml"
hash = "7969168fd1ac5792dcbfcc73ae7c3ef118fe2585586357d276ab5d172280ff62"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "502cd535f6cda8e1e0b0cf83a785e8d8f5702f18b8902ae0c765952d8cfe0b4a"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "399e2642bdf663c6352d6560f4f48e903750e889e1b78c731d240caf0c6a2e28"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fec143d68112c0260e4964f50aad541afde432252cd3f748d4046267af558e67"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "ded057bbb3ab2991addbf96e472df8efa7434c3060f65f6e4d95491c488e659c"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "6c23d726c5512cc285114ee243192dab6ddf39135f273e1fa8e1aec6b0df80d3"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "77f83db2fae27b75a36910d16d01e4d483d2231de3fc68d2a634eb93ec2de7c5"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79abdb9bafc3793dd8c51e633667c20cb85f9dbfdad0d008bbca8be26f22cbf3"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a6c1b4971c7c06b4a6e802362ae24feb242ae2943cef941fe6319b651768b7e1"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "773f8e897a0a3b196383e5c4552643fa88708cd02dbd18be4396d4c63557781e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dc27377674c79509779c7b17d7db80748d9636c5d639b0e5f67f90b45f1a8e5"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "c6c1956834ce20306f66fcdaa8a9b193556c431851f20570436f82be08d52ac7"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "32ab4cf00cde6b04c1a699789487ba55913bdd41ea46bb45748a6373e1fc9b29"
metafile = true

[[files]]
file = "mods/nmuk.pw.toml"
hash = "bdbc686eb9ec1da8e9bf5013e2615289ec2e6a0d822323f9df6589acdf5da991"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "51b735f00031dc7ddbb390dae266953bfbab4e7a3018a824751b149757489a4a"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "c30e913faf036c06fe93c3082d18e422a49470a675225cb13f964efc70a9babb"
metafile = true

[[files]]
file = "mods/purpeille.pw.toml"
hash = "80981a29055f333485e8b28d4099a7e6342bd50a9cc98952deb13f7a488caa49"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "634f149e6233a59ceb725e796300c81ac8f19d281c49dd778fdd9b591cd79d5d"
metafile = true

[[files]]
file = "mods/red-bits.pw.toml"
hash = "db1a43eca0fdecddf78f31bfd71e7f6a58aee05427876fdeaa80ab2437eee0b5"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b62d450c909c7edb4b677b6ffff2f9f582db060bd7b457d7a59490547750df71"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "c0e2ebc766c8680d6845ed6694f5d89ab418f67217059320d681b5d1ccdac502"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9346d09f897be45df79ad6af92e38f34f650ca557e65bc199f629021bbcff915"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8a2f7bd4e0b892213e121ace77cbe399351a8c9d1ce12a8dc13973d9ec7a50dc"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f95b2fb43d80577d8f42bb6c60bd0e7aafe7db81a43e5122b7ee69941fccbaeb"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2140367d53fc14e3223ffed3802bd3a0c6548208458e0dd4aecd040d8b04cf4e"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "b51973797d0cc8b656e71b85c4a2143995a4bb599181453ef9b0e7e6e3de549f"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "974cb82e9887e1821a27caccb506068d4a6051c4def25cfc566d3bdc00d1bc95"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "4e8c0ff9e26efaed02012b22b6c75768a0ff03cc969f7050e0eddf0548948f5f"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "b6264f0d5c72e58deb43b1081574d443d870edf06f4ddea833814d41f07994b2"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "cf7587112d781431bba84480b54cd7735a828e9c82acd40b6011f9ce64a1faf7"
metafile = true

[[files]]
file = "mods/wandering-collector.pw.toml"
hash = "8a7afba25952c2be4f81a8896b9ceb0fe365407b85b810f770a85f3e801acd54"
metafile = true

[[files]]
file = "mods/wmitaf.pw.toml"
hash = "46591cb208ca0e86146949af7065e856d9a8080dc6737b4fac09de7c30d833d4"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "c7aaa1a6c17b3a05f727ee143868595eab4fd3ac6348d2ceded5f04aa4d9fb6c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "61e328b0d9324fb4f713a5e1a7aed8a97ead1de33f7496a623e6028e2b4544f5"
metafile = true
