name = "QuiltWiz"
author = "Nemo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "247fb544b6c258a41b0eb0871f879ae684babed1ea914566b072da96c6179142"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
