name = "CarbonQuiltWiz"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "835393a28b19dc88b8849f65d1eaff86abec34af76fbce8cf377048af048af10"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
