name = "CarbonQuilt 1.19"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "380de1b18f13b4fe431acc3c26c9ad9e2613db701894f9178a97bbe50c8d5eb8"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
