name = "CarbonQuiltWiz"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d4f756630e019ecba9f64c425eda3ec6640e749ebecc2e573be873deeccce30"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
