name = "CarbonQuilt 1.19"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d693b50c9c5ef067b2cc27eab82d368cdfec24d9544b2f235d494314f049158b"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
