name = "CarbonQuiltWiz"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d6bf0bb280b69cecef26348669110639d33b1da118e6bd974c8d5b6edd8aa9b"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
