name = "CarbonQuiltWiz"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab9e2aef9a89700926439f138f59ba4ef9307ac7aad194bf7344411b681b41d"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
