name = "CarbonQuiltWiz"
author = "Nemal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73aef4ba2db4ce3b752fcaf04816d4eba7bb156d11758176669013a63ce8f488"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
